import 'package:flutter/material.dart';
import 'models.dart';

/// 演示数据（IM / 支付 / 短视频 / 商城 / 小程序 / 本地生活）
/// 说明：新闻走本机真实 API；其余为完整可用的本地业务数据（下单、退款、账单、评论都会真实改变这里的状态）
class Mock {
  static final now = DateTime.now();

  // ============================================================
  // 短视频 / 直播（asset 指向本地真实视频文件，走 video_player 解码播放）
  // ============================================================
  static const List<VideoItem> videos = [
    VideoItem(
      id: 'v1',
      title: '现场：城市地铁新线开通首日实拍',
      titleEn: 'Live: Metro new line opens',
      author: '寰宇现场',
      authorEn: 'Huanyu Live',
      desc: '#城市观察 #交通 #实拍',
      descEn: '#City #Transit #Live',
      likes: 128000,
      comments: 3421,
      shares: 8920,
      seed: ColorSeed(Color(0xFF1E3C72), Color(0xFF2A5298)),
      tags: ['城市观察', '交通', '实拍'],
      asset: 'assets/videos/clip1.mp4',
      productIds: ['p6', 'p9'],
      shop: '寰宇严选',
    ),
    VideoItem(
      id: 'v2',
      title: '直播：财经早班车 · 今日开盘解读',
      titleEn: 'Live: Market open briefing',
      author: '寰宇财经',
      authorEn: 'Huanyu Finance',
      desc: '#财经直播 #开盘 #解读',
      descEn: '#Finance #Market #Opening',
      likes: 86400,
      comments: 12030,
      shares: 2100,
      live: true,
      viewers: 23681,
      seed: ColorSeed(Color(0xFFB02E0C), Color(0xFFFE2C55)),
      tags: ['财经', '直播', '开盘'],
      asset: 'assets/videos/clip2.mp4',
      productIds: ['p5'],
      shop: '寰宇文创',
    ),
    VideoItem(
      id: 'v3',
      title: '三分钟看懂人工智能最新进展',
      titleEn: 'AI explained in 3 minutes',
      author: '科技观察局',
      authorEn: 'Tech Watch',
      desc: '#科技 #AI #科普',
      descEn: '#Tech #AI #Explained',
      likes: 231000,
      comments: 15600,
      shares: 31200,
      seed: ColorSeed(Color(0xFF0F2027), Color(0xFF2C5364)),
      tags: ['科技', 'AI', '科普'],
      asset: 'assets/videos/clip3.mp4',
      productIds: ['p2', 'p10'],
      shop: '声海数码专营店',
    ),
    VideoItem(
      id: 'v4',
      title: '深夜食堂：城市里的烟火气',
      titleEn: 'Midnight diner in the city',
      author: '生活家',
      authorEn: 'Life Guru',
      desc: '#美食 #夜宵 #探店',
      descEn: '#Food #Midnight #Eats',
      likes: 45200,
      comments: 2310,
      shares: 1890,
      seed: ColorSeed(Color(0xFF42275A), Color(0xFF734B6D)),
      tags: ['美食', '夜宵', '探店'],
      asset: 'assets/videos/clip1.mp4',
      productIds: ['p8', 'p3'],
      shop: '云谷食品',
    ),
    VideoItem(
      id: 'v5',
      title: '直播：国际局势一周盘点',
      titleEn: 'Live: Weekly global review',
      author: '寰宇国际',
      authorEn: 'Huanyu World',
      desc: '#国际 #时政 #盘点',
      descEn: '#World #Politics #Weekly',
      likes: 67200,
      comments: 8930,
      shares: 4300,
      live: true,
      viewers: 15230,
      seed: ColorSeed(Color(0xFF232526), Color(0xFF414345)),
      tags: ['国际', '时政', '直播'],
      asset: 'assets/videos/clip2.mp4',
      productIds: ['p5', 'p7'],
      shop: '寰宇严选',
    ),
  ];

  // ============================================================
  // 视频评论（进入消息中心，可回复）
  // ============================================================
  static final List<VideoComment> comments = [
    VideoComment(
      id: 'c1',
      videoId: 'v1',
      author: '城市观察者',
      seed: ColorSeed(Color(0xFF43A047), Color(0xFF66BB6A)),
      text: '这条线我等了三年，今天首发就去体验了，真的快很多。',
      time: now.subtract(const Duration(hours: 2)),
      likes: 1280,
      pinned: true,
    ),
    VideoComment(
      id: 'c2',
      videoId: 'v1',
      author: '通勤小达人',
      seed: ColorSeed(Color(0xFF1677FF), Color(0xFF3F8CFF)),
      text: '早高峰从城西到中心只要 28 分钟，同款通勤包已下单。',
      time: now.subtract(const Duration(hours: 1)),
      likes: 862,
    ),
    VideoComment(
      id: 'c3',
      videoId: 'v1',
      author: '老张',
      seed: ColorSeed(Color(0xFFFF9800), Color(0xFFFFB74D)),
      text: '希望首末班车时间能再延长一点。',
      time: now.subtract(const Duration(minutes: 48)),
      likes: 233,
    ),
    VideoComment(
      id: 'c4',
      videoId: 'v2',
      author: 'K线图日记',
      seed: ColorSeed(Color(0xFF8E24AA), Color(0xFFAB47BC)),
      text: '老师讲得很清楚，开盘前听一遍心里有底了。',
      time: now.subtract(const Duration(minutes: 32)),
      likes: 4210,
      pinned: true,
    ),
    VideoComment(
      id: 'c5',
      videoId: 'v2',
      author: '稳健投资人',
      seed: ColorSeed(Color(0xFF0083B0), Color(0xFF00B4DB)),
      text: '合订本已买，希望能系统复盘一下今年的行情。',
      time: now.subtract(const Duration(minutes: 21)),
      likes: 1180,
    ),
    VideoComment(
      id: 'c6',
      videoId: 'v2',
      author: '财经小白',
      seed: ColorSeed(Color(0xFFF4511E), Color(0xFFFF7043)),
      text: '有没有新手友好的入门书推荐？',
      time: now.subtract(const Duration(minutes: 9)),
      likes: 96,
    ),
    VideoComment(
      id: 'c7',
      videoId: 'v3',
      author: '算法爱好者',
      seed: ColorSeed(Color(0xFF0F2027), Color(0xFF2C5364)),
      text: '三分钟讲透了大模型推理的核心，收藏了。',
      time: now.subtract(const Duration(hours: 3)),
      likes: 8620,
      pinned: true,
    ),
    VideoComment(
      id: 'c8',
      videoId: 'v3',
      author: '数码控',
      seed: ColorSeed(Color(0xFF6A11CB), Color(0xFF2575FC)),
      text: '挂在小黄车的那款降噪耳机我买了，通勤戴很香。',
      time: now.subtract(const Duration(hours: 1)),
      likes: 2310,
    ),
    VideoComment(
      id: 'c9',
      videoId: 'v4',
      author: '深夜饿了吗',
      seed: ColorSeed(Color(0xFF42275A), Color(0xFF734B6D)),
      text: '看完直接下单一盒零食，罪恶但快乐。',
      time: now.subtract(const Duration(minutes: 40)),
      likes: 1780,
    ),
    VideoComment(
      id: 'c10',
      videoId: 'v4',
      author: '咖啡续命',
      seed: ColorSeed(Color(0xFF8E2DE2), Color(0xFF4A00E0)),
      text: '挂耳咖啡配夜宵，是打工人的浪漫。',
      time: now.subtract(const Duration(minutes: 18)),
      likes: 920,
    ),
    VideoComment(
      id: 'c11',
      videoId: 'v5',
      author: '世界观',
      seed: ColorSeed(Color(0xFF232526), Color(0xFF414345)),
      text: '一周盘点做得很扎实，已经推荐给同事了。',
      time: now.subtract(const Duration(minutes: 25)),
      likes: 3120,
      pinned: true,
    ),
    VideoComment(
      id: 'c12',
      videoId: 'v5',
      author: '前线小记者',
      seed: ColorSeed(Color(0xFFB02E0C), Color(0xFFFE2C55)),
      text: '直播间的合订本还有货吗？',
      time: now.subtract(const Duration(minutes: 6)),
      likes: 210,
    ),
  ];

  // ============================================================
  // 互动消息（点赞 / 评论 / 关注 / 直播）——统一进入消息中心
  // ============================================================
  static final List<InteractionMsg> interactions = [
    InteractionMsg(
      id: 'i1',
      type: InteractType.comment,
      videoId: 'v1',
      videoTitle: '现场：城市地铁新线开通首日实拍',
      user: '通勤小达人',
      userEn: 'Commuter',
      avatarText: '达',
      seed: ColorSeed(Color(0xFF1677FF), Color(0xFF3F8CFF)),
      text: '早高峰从城西到中心只要 28 分钟，同款通勤包已下单。',
      time: now.subtract(const Duration(hours: 1)),
    ),
    InteractionMsg(
      id: 'i2',
      type: InteractType.like,
      videoId: 'v3',
      videoTitle: '三分钟看懂人工智能最新进展',
      user: '数码控',
      userEn: 'Gadget Fan',
      avatarText: '控',
      seed: ColorSeed(Color(0xFF6A11CB), Color(0xFF2575FC)),
      text: '赞了你的作品',
      time: now.subtract(const Duration(minutes: 52)),
    ),
    InteractionMsg(
      id: 'i3',
      type: InteractType.follow,
      videoId: 'v2',
      videoTitle: '直播：财经早班车 · 今日开盘解读',
      user: '稳健投资人',
      userEn: 'Steady Investor',
      avatarText: '投',
      seed: ColorSeed(Color(0xFF0083B0), Color(0xFF00B4DB)),
      text: '关注了你',
      time: now.subtract(const Duration(minutes: 30)),
    ),
    InteractionMsg(
      id: 'i4',
      type: InteractType.live,
      videoId: 'v5',
      videoTitle: '直播：国际局势一周盘点',
      user: '寰宇国际',
      userEn: 'Huanyu World',
      avatarText: '国',
      seed: ColorSeed(Color(0xFF232526), Color(0xFF414345)),
      text: '你关注的直播间开播了，1.5 万人正在观看',
      time: now.subtract(const Duration(minutes: 12)),
    ),
    InteractionMsg(
      id: 'i5',
      type: InteractType.order,
      videoId: 'v3',
      videoTitle: '三分钟看懂人工智能最新进展',
      user: '寰宇商城',
      userEn: 'Huanyu Shop',
      avatarText: '商',
      seed: ColorSeed(Color(0xFFFE2C55), Color(0xFFFF6B8B)),
      text: '来自本视频的订单已支付成功',
      time: now.subtract(const Duration(minutes: 3)),
    ),
  ];

  // ============================================================
  // 商城商品（淘宝级字段：SKU / 评分 / 月销 / 优惠券 / 服务承诺）
  // ============================================================
  static final List<Product> products = [
    Product(
      id: 'p1',
      category: 'fashion',
      title: '寰宇定制 纯棉圆领短袖T恤 多色可选',
      titleEn: 'Huanyu Cotton Crew Neck Tee',
      shop: '寰宇官方旗舰店',
      shopEn: 'Huanyu Official',
      price: 89.0,
      origin: 159.0,
      sold: 12830,
      salesMonthly: 4218,
      rating: 4.9,
      reviewCount: 8621,
      seed: ColorSeed(Color(0xFF6A11CB), Color(0xFF2575FC)),
      tag: '包邮',
      coupons: ['满99减10', '关注店铺减5'],
      specs: ['颜色', '尺码'],
      specOptions: ['曜石黑', '云雾白', '雾霾蓝'],
      highlights: ['260g 精梳棉', '三线车缝不易变形', '水洗不褪色'],
      videoId: 'v1',
      images: ['assets/shop/p1_1.jpg', 'assets/shop/p1_2.jpg', 'assets/shop/p1_3.jpg'],
      desc: '260g 重磅精梳棉，双面纱工艺，领口三线车缝久洗不变形，缩水率控制在 3% 以内。',
      descEn: '260g combed cotton, reinforced collar, shrink under 3%.',
      detail: ['面料：100% 长绒棉 260g/㎡', '工艺：三线车缝 + 双针下摆', '版型：常规直筒，肩线贴合'],
    ),
    Product(
      id: 'p2',
      category: 'digital',
      title: '无线蓝牙耳机 主动降噪 超长续航',
      titleEn: 'Wireless Earbuds ANC Long Battery',
      shop: '声海数码专营店',
      shopEn: 'Shenghai Digital',
      price: 299.0,
      origin: 499.0,
      sold: 8632,
      salesMonthly: 3120,
      rating: 4.8,
      reviewCount: 12980,
      seed: ColorSeed(Color(0xFF0F2027), Color(0xFF203A43)),
      tag: '12期免息',
      coupons: ['满300减30'],
      specs: ['颜色'],
      specOptions: ['石墨黑', '珍珠白'],
      highlights: ['42dB 深度降噪', '单次 9 小时续航', '入耳检测'],
      images: ['assets/shop/p2_1.jpg', 'assets/shop/p2_2.jpg', 'assets/shop/p2_3.jpg'],
      desc: '双馈麦克风 + 42dB 主动降噪，通勤地铁与开放办公室都能安静下来；单次续航 9 小时，配充电仓共 36 小时。',
      descEn: '42dB hybrid ANC, 9h per charge and 36h with the case.',
      detail: ['单元：12.4mm 动圈', '降噪：双馈 ANC 42dB', '续航：9h + 27h 充电仓'],
      videoId: 'v3',
    ),
    Product(
      id: 'p3',
      category: 'food',
      title: '云南小粒咖啡 挂耳咖啡 30 片装',
      titleEn: 'Yunnan Arabica Drip Coffee 30pcs',
      shop: '云谷食品',
      shopEn: 'Yungu Foods',
      price: 59.9,
      origin: 99.0,
      sold: 23108,
      salesMonthly: 9820,
      rating: 4.9,
      reviewCount: 21308,
      seed: ColorSeed(Color(0xFF8E2DE2), Color(0xFF4A00E0)),
      tag: '新品',
      coupons: ['满59减6', '第二件半价'],
      specs: ['口味'],
      specOptions: ['醇香款', '果酸款', '混合装'],
      highlights: ['云南保山产区', '中深烘焙', '氮气锁鲜'],
      images: ['assets/shop/p3_1.jpg', 'assets/shop/p3_2.jpg', 'assets/shop/p3_3.jpg'],
      desc: '云南保山小粒咖啡，中深烘焙，坚果与黑巧风味突出；独立氮气锁鲜挂耳包，30 片装，办公室与出差都方便。',
      descEn: 'Yunnan arabica, medium-dark roast, nitrogen-sealed drip bags, 30 packs.',
      detail: ['产区：云南保山 高黎贡山', '烘焙度：中深（Agtron 58）', '规格：10g × 30 片'],
      videoId: 'v4',
    ),
    Product(
      id: 'p4',
      category: 'digital',
      title: '智能手环 血氧心率监测 运动防水',
      titleEn: 'Smart Band SpO2 Heart Rate',
      shop: '智行运动',
      shopEn: 'Zhixing Sports',
      price: 199.0,
      origin: 329.0,
      sold: 5421,
      salesMonthly: 1876,
      rating: 4.7,
      reviewCount: 5320,
      seed: ColorSeed(Color(0xFF00B4DB), Color(0xFF0083B0)),
      tag: '爆款',
      coupons: ['满199减20'],
      specs: ['表带颜色'],
      specOptions: ['暗夜黑', '樱花粉', '松柏绿'],
      highlights: ['14 天续航', '5ATM 防水', '全天血氧监测'],
      images: ['assets/shop/p4_1.jpg', 'assets/shop/p4_2.jpg', 'assets/shop/p4_3.jpg'],
      desc: '1.47 英寸 AMOLED 大屏，全天血氧与心率监测，支持 120 种运动模式；5ATM 防水，14 天超长续航。',
      descEn: '1.47" AMOLED, 24h SpO2 and heart-rate, 120 sport modes, 5ATM.',
      detail: ['屏幕：1.47 英寸 AMOLED', '传感器：血氧 + 心率 + 睡眠', '续航：典型 14 天'],
    ),
    Product(
      id: 'p5',
      category: 'books',
      title: '寰宇新闻 2026 年度精选合订本',
      titleEn: 'Huanyu News Annual Collection 2026',
      shop: '寰宇文创',
      shopEn: 'Huanyu Culture',
      price: 128.0,
      origin: 168.0,
      sold: 1982,
      salesMonthly: 862,
      rating: 5.0,
      reviewCount: 1082,
      seed: ColorSeed(Color(0xFFFC4A1A), Color(0xFFF7B733)),
      tag: '限量',
      coupons: ['直播间专享减20'],
      specs: ['装帧'],
      specOptions: ['精装版', '典藏版'],
      highlights: ['全年度深度报道', '编辑部亲笔手记', '限量编号'],
      images: ['assets/shop/p5_1.jpg', 'assets/shop/p5_2.jpg', 'assets/shop/p5_3.jpg'],
      desc: '收录寰宇新闻 2026 年度 48 篇深度报道与调查手记，附编辑部亲笔后记；限量编号发行，硬壳精装 396 页。',
      descEn: '48 in-depth reports of 2026 with editors’ notes, hardcover 396 pages.',
      detail: ['页数：396 页 硬壳精装', '收录：48 篇深度报道 + 12 篇手记', '发行：限量编号 5000 册'],
      videoId: 'v2',
    ),
    Product(
      id: 'p6',
      category: 'fashion',
      title: '真皮商务手提包 大容量通勤包',
      titleEn: 'Leather Business Tote',
      shop: '匠心皮具',
      shopEn: 'Artisan Leather',
      price: 599.0,
      origin: 1099.0,
      sold: 763,
      salesMonthly: 218,
      rating: 4.8,
      reviewCount: 763,
      seed: ColorSeed(Color(0xFF232526), Color(0xFF414345)),
      tag: '品质',
      coupons: ['满599减50'],
      specs: ['颜色'],
      specOptions: ['经典黑', '复古棕'],
      highlights: ['头层牛皮', '独立电脑仓', '手工缝线'],
      images: ['assets/shop/p6_1.jpg', 'assets/shop/p6_2.jpg', 'assets/shop/p6_3.jpg'],
      desc: '意大利头层牛皮，独立 16 英寸电脑仓与文件隔层；黄铜五金 + 手工缝线，通勤与差旅都能装。',
      descEn: 'Italian full-grain leather, 16" laptop compartment, brass hardware.',
      detail: ['材质：头层牛皮（1.4mm）', '容量：16 英寸笔电 + A4 文件', '五金：黄铜拉链，手工缝线'],
      videoId: 'v1',
    ),
    Product(
      id: 'p7',
      category: 'home',
      title: '便携无线榨汁杯 隨行 CJ-300',
      titleEn: 'Portable Blender CJ-300',
      shop: '寰宇严选',
      shopEn: 'Huanyu Select',
      price: 79.0,
      origin: 129.0,
      sold: 31208,
      salesMonthly: 12830,
      rating: 4.6,
      reviewCount: 23108,
      seed: ColorSeed(Color(0xFF43A047), Color(0xFF66BB6A)),
      tag: '直播爆品',
      coupons: ['直播间减30'],
      specs: ['容量'],
      specOptions: ['300ml', '420ml'],
      highlights: ['Type-C 快充', '一键清洗', '食品级材质'],
      images: ['assets/shop/p7_1.jpg', 'assets/shop/p7_2.jpg', 'assets/shop/p7_3.jpg'],
      desc: '380ml 随行榨汁杯，304 不锈钢四叶刀头，30 秒出汁；Type-C 快充，满电可榨 12 杯，一键拆洗。',
      descEn: '380ml portable blender, 304 steel blades, 12 cups per charge.',
      detail: ['容量：380ml 随行杯', '刀头：304 不锈钢四叶', '电池：2000mAh Type-C 快充'],
      videoId: 'v5',
    ),
    Product(
      id: 'p8',
      category: 'food',
      title: '海苔可可 illumin 零食礼盒 12 件',
      titleEn: 'Snack Gift Box 12pcs',
      shop: '云谷食品',
      shopEn: 'Yungu Foods',
      price: 39.9,
      origin: 69.0,
      sold: 18230,
      salesMonthly: 7621,
      rating: 4.7,
      reviewCount: 9218,
      seed: ColorSeed(Color(0xFFF4511E), Color(0xFFFF7043)),
      tag: '零食党',
      coupons: ['买二送一'],
      specs: ['口味组合'],
      specOptions: ['微辣组合', '原味组合'],
      highlights: ['12 件装', '独立小包装', '7 天短保新鲜'],
      images: ['assets/shop/p8_1.jpg', 'assets/shop/p8_2.jpg', 'assets/shop/p8_3.jpg'],
      desc: '海苔 + 可可组合零食礼盒，12 件独立小包装；7 天短保现做现发，办公室下午茶与送礼都合适。',
      descEn: 'Seaweed and cocoa snack box, 12 individually packed pieces.',
      detail: ['规格：12 件独立小包装', '保质期：7 天短保现发', '口味：海苔 6 + 可可 6'],
      videoId: 'v4',
    ),
    Product(
      id: 'p9',
      category: 'sports',
      title: '轻量减震跑鞋 全掌碳板',
      titleEn: 'Lightweight Running Shoes',
      shop: '智行运动',
      shopEn: 'Zhixing Sports',
      price: 399.0,
      origin: 699.0,
      sold: 4218,
      salesMonthly: 1520,
      rating: 4.8,
      reviewCount: 3120,
      seed: ColorSeed(Color(0xFF43A047), Color(0xFF66BB6A)),
      tag: '运动',
      coupons: ['满399减40'],
      specs: ['颜色', '尺码'],
      specOptions: ['荧光绿', '石墨黑'],
      highlights: ['全掌碳板', '回弹中底', '透气飞织鞋面'],
      images: ['assets/shop/p9_1.jpg', 'assets/shop/p9_2.jpg', 'assets/shop/p9_3.jpg'],
      desc: '全掌铲型碳板 + 超临界发泡中底，回弹率 78%；单只仅 198g，飞织鞋面透气不闷脚，适合节奏跑与半马。',
      descEn: 'Full-length carbon plate, 78% energy return, 198g per shoe.',
      detail: ['中底：超临界发泡 + 全掌碳板', '重量：单只 198g（42 码）', '鞋面：工程飞织透气'],
      videoId: 'v1',
    ),
    Product(
      id: 'p10',
      category: 'home',
      title: '铝合金显示器支架 桌面升降',
      titleEn: 'Aluminum Monitor Stand',
      shop: '匠心家居',
      shopEn: 'Artisan Home',
      price: 259.0,
      origin: 359.0,
      sold: 2310,
      salesMonthly: 692,
      rating: 4.9,
      reviewCount: 1820,
      seed: ColorSeed(Color(0xFF6A11CB), Color(0xFF2575FC)),
      tag: '居家',
      coupons: ['满259减30'],
      specs: ['颜色'],
      specOptions: ['深空灰', '银色'],
      highlights: ['支持 27 寸', '无级阻尼', '隐藏走线'],
      images: ['assets/shop/p10_1.jpg', 'assets/shop/p10_2.jpg', 'assets/shop/p10_3.jpg'],
      desc: '铝合金一体成型，承重 12kg 适配 17-32 英寸显示器；无级阻尼升降，底座隐藏走线，桌面更整洁。',
      descEn: 'Aluminum arm holds up to 12kg, fits 17-32" monitors, hidden cable routing.',
      detail: ['材质：航空铝合金', '适配：17-32 英寸 / VESA 75·100', '调节：升降 260mm + 360° 旋转'],
      videoId: 'v3',
    ),
  ];

  /// 商品评价（宝贝详情页的评价区）
  static final List<Map<String, dynamic>> reviews = [
    {
      'user': '林***8',
      'rating': 5.0,
      'spec': '曜石黑 / XL',
      'text': '面料厚实，洗过一次没有变形，物流也很快。',
      'replies': ['感谢支持，后续上新记得来看~'],
    },
    {
      'user': '陈***2',
      'rating': 4.0,
      'spec': '云雾白 / L',
      'text': '版型挺括，唯一的问题是有轻微线头，不影响穿着。',
      'replies': ['已反馈品控，会持续改进，给您补了优惠券~'],
    },
    {
      'user': 'W***n',
      'rating': 5.0,
      'spec': '雾霾蓝 / M',
      'text': '第二次回购了，客服态度好，发货速度很快。',
      'replies': [],
    },
  ];

  // ============================================================
  // 本地生活（对标美团）
  // ============================================================
  static const List<LocalDeal> deals = [
    LocalDeal(
      id: 'd1',
      title: '老碗村 · 双人套餐',
      titleEn: 'Laowan Village: Set for 2',
      shop: '老碗村（文一西路店）',
      category: DealCategory.group,
      price: 98.0,
      origin: 216.0,
      sold: 3821,
      rating: 4.8,
      distanceKm: 0.8,
      address: '余杭区文一西路 889 号',
      seed: ColorSeed(Color(0xFFFF9800), Color(0xFFFFB74D)),
      tags: ['免预约', '随时退'],
      packageItems: ['招牌牛肉面 x2', '凉拌木耳', '酸梅汤 x2'],
      openHours: '10:30-21:30',
      image: 'assets/life/d1.jpg',
      desc: '文一西路人气面馆，招牌牛肉面筋道入味，双人套餐含两份主食与酸梅汤，周末通用不加价。',
      descEn: 'Signature beef noodles for two at a popular local noodle house.',
    ),
    LocalDeal(
      id: 'd2',
      title: '云谷咖啡 · 单品手冲兑换券',
      titleEn: 'Yungu Coffee: Pour-over voucher',
      shop: '云谷咖啡（未来城店）',
      category: DealCategory.group,
      price: 29.9,
      origin: 58.0,
      sold: 12830,
      rating: 4.9,
      distanceKm: 1.5,
      address: '余杭区未来科技城 A 座',
      seed: ColorSeed(Color(0xFF8E2DE2), Color(0xFF4A00E0)),
      tags: ['随时退', '过期退'],
      packageItems: ['单品手冲咖啡 x1'],
      openHours: '08:00-21:00',
      image: 'assets/life/d2.jpg',
      desc: '精品咖啡馆单品手冲兑换券，耶加雪菲 / 曼特宁二选一，咖啡师现场冲煮，店内堂食或外带均可。',
      descEn: 'Single-origin pour-over voucher, Yirgacheffe or Mandheling.',
    ),
    LocalDeal(
      id: 'd3',
      title: '寰宇商城 · 30 分钟闪送',
      titleEn: 'Huanyu Express: 30min delivery',
      shop: '寰宇商城即时配送',
      category: DealCategory.takeaway,
      price: 6.0,
      origin: 12.0,
      sold: 89320,
      rating: 4.7,
      distanceKm: 0.0,
      address: '全城配送',
      seed: ColorSeed(Color(0xFFFE2C55), Color(0xFFFF6B8B)),
      tags: ['准时达', '超时赔付'],
      packageItems: ['全城 30 分钟送达', '首单立减 6 元'],
      deliveryNow: true,
      image: 'assets/life/d3.jpg',
      desc: '3 公里内 30 分钟必达，超时立赔；专职骑手取送，生鲜、药品、文件都能寄，首单立减 6 元。',
      descEn: 'Delivery within 30 minutes in 3km, late orders compensated.',
    ),
    LocalDeal(
      id: 'd4',
      title: '余杭亚朵酒店 · 大床房 1 晚',
      titleEn: 'Atour Hotel: 1 night',
      shop: '亚朵酒店（余杭店）',
      category: DealCategory.hotel,
      price: 458.0,
      origin: 699.0,
      sold: 2310,
      rating: 4.8,
      distanceKm: 3.2,
      address: '余杭区五常大道 88 号',
      seed: ColorSeed(Color(0xFF0083B0), Color(0xFF00B4DB)),
      tags: ['含双早', '免费取消'],
      packageItems: ['高级大床房 1 晚', '双人自助早餐', '免费停车'],
      image: 'assets/life/d4.jpg',
      desc: '未来科技城商圈，步行可达地铁 5 号线；含双人自助早餐与免费停车，入住当天 18:00 前可免费取消。',
      descEn: 'King room for one night with breakfast and free parking.',
    ),
    LocalDeal(
      id: 'd5',
      title: '星光影城 · 2D/3D 通兑券',
      titleEn: 'Star Cinema: movie voucher',
      shop: '星光影城（城西银泰店）',
      category: DealCategory.movie,
      price: 39.9,
      origin: 80.0,
      sold: 23180,
      rating: 4.6,
      distanceKm: 4.5,
      address: '西湖区丰潭路 380 号',
      seed: ColorSeed(Color(0xFF6A11CB), Color(0xFF2575FC)),
      tags: ['不限场次', '周末通用'],
      packageItems: ['2D/3D 电影票 x1'],
      image: 'assets/life/d5.jpg',
      desc: '全城 6 家门店通兑，2D/3D 均可使用，节假日不加价；激光厅与杜比厅需现场补差价，购票后 30 天有效。',
      descEn: 'One 2D/3D movie ticket valid at 6 cinemas citywide.',
    ),
    LocalDeal(
      id: 'd6',
      title: '木源造型 · 洗剪吹套餐',
      titleEn: 'Muyuan Salon: hair cut',
      shop: '木源造型（未来城店）',
      category: DealCategory.beauty,
      price: 88.0,
      origin: 168.0,
      sold: 5821,
      rating: 4.7,
      distanceKm: 1.1,
      address: '余杭区海创园 18 号',
      seed: ColorSeed(Color(0xFFF4511E), Color(0xFFFF7043)),
      tags: ['免预约', '指定总监'],
      packageItems: ['总监洗剪吹 x1', '头皮护理'],
      image: 'assets/life/d6.jpg',
      desc: '总监级发型师一对一服务，含头皮检测与深层清洁；免预约到店，周末及节假日通用。',
      descEn: 'Wash, cut and style by a senior stylist plus scalp care.',
    ),
    LocalDeal(
      id: 'd7',
      title: '家电清洗 · 空调深度拆洗',
      titleEn: 'AC deep cleaning',
      shop: '净家到家服务',
      category: DealCategory.repair,
      price: 129.0,
      origin: 199.0,
      sold: 3820,
      rating: 4.9,
      distanceKm: 0.0,
      address: '全城上门',
      seed: ColorSeed(Color(0xFF43A047), Color(0xFF66BB6A)),
      tags: ['专业工具', '不满意重做'],
      packageItems: ['挂机空调拆洗 x2', '高温杀菌'],
      image: 'assets/life/d7.jpg',
      desc: '挂机空调深度拆洗，含滤网、风轮、蒸发器高温蒸汽杀菌；师傅持证上门，施工全程铺设保护垫。',
      descEn: 'Deep cleaning for two wall-mounted AC units with steam sterilization.',
    ),
    LocalDeal(
      id: 'd8',
      title: '西溪湿地 · 门票+观光车',
      titleEn: 'Xixi Wetland: entry + shuttle',
      shop: '西溪湿地公园',
      category: DealCategory.travel,
      price: 78.0,
      origin: 120.0,
      sold: 9230,
      rating: 4.8,
      distanceKm: 6.8,
      address: '西湖区天目山路 518 号',
      seed: ColorSeed(Color(0xFF00B4DB), Color(0xFF0083B0)),
      tags: ['当天可用', '无需换票'],
      packageItems: ['成人门票 x1', '园内观光车'],
      image: 'assets/life/d8.jpg',
      desc: '西溪湿地成人门票一张，含园内观光车/电瓶船二选一；当次入园有效，无需预约，周末通用。',
      descEn: 'Xixi Wetland entry ticket with shuttle bus or electric boat.',
    ),
  ];

  // ============================================================
  // 即时通讯会话（replies 用于模拟对方自动回复）
  // ============================================================
  static final List<ChatSession> sessions = [
    ChatSession(
      id: 's1',
      name: '寰宇编辑部',
      nameEn: 'Huanyu Editorial',
      avatarText: '编',
      seed: const ColorSeed(Color(0xFF07C160), Color(0xFF0BA84A)),
      lastMessage: '今天的头条稿已经过审，可以发布了',
      lastMessageEn: 'Today\'s headline is approved, go publish',
      time: now.subtract(const Duration(minutes: 3)),
      unread: 3,
      isGroup: true,
      pinned: true,
      messages: const [],
      replies: const [
        '收到，我同步给前端同学排期。',
        '现在我们先确认下标题的分寸感，看看要不要再打磨一下。',
        '这条新闻配图用 niko 那张实景图，比旧图更有现场感。',
        '好的，我十分钟后给出修改版。',
      ],
    ),
    ChatSession(
      id: 's2',
      name: '林记者',
      nameEn: 'Reporter Lin',
      avatarText: '林',
      seed: const ColorSeed(Color(0xFF1677FF), Color(0xFF3F8CFF)),
      lastMessage: '现场图片我上传到你邮箱了',
      lastMessageEn: 'Photos uploaded to your mailbox',
      time: now.subtract(const Duration(minutes: 28)),
      unread: 1,
      messages: const [],
      replies: const [
        '马上给你补一个现场视频素材。',
        '我已经到现场了，采访对象十分钟后到。',
        '这份材料我核对过两遍，数据没有问题。',
        '路上信号不太好，稍等我到地方再回。',
      ],
    ),
    ChatSession(
      id: 's3',
      name: '家庭群',
      nameEn: 'Family',
      avatarText: '家',
      seed: const ColorSeed(Color(0xFFFF9800), Color(0xFFFFB74D)),
      lastMessage: '晚上回来吃饭吗',
      lastMessageEn: 'Coming home for dinner?',
      time: now.subtract(const Duration(hours: 1)),
      unread: 5,
      isGroup: true,
      messages: const [],
      replies: const [
        '回来吃，大概七点到家。',
        '妈，我晚上要加班，你们先吃。',
        '我给你留了汤，在灶台上热着。',
        '周末我们大家一起去爬山吧。',
      ],
    ),
    ChatSession(
      id: 's4',
      name: '寰宇商城客服',
      nameEn: 'Huanyu Shop Support',
      avatarText: '客',
      seed: const ColorSeed(Color(0xFFFE2C55), Color(0xFFFF6B8B)),
      lastMessage: '您好，您的订单已发货，请注意查收',
      lastMessageEn: 'Your order has been shipped',
      time: now.subtract(const Duration(minutes: 12)),
      unread: 2,
      official: true,
      messages: const [],
      replies: const [
        '您好，我是商城客服小宇，请问有什么可以帮您？',
        '您的包裹已交给顺丰，物流单号稍后发您。',
        '未发货订单支持秒退款，我这边可以直接帮您操作。',
        '需要开发票的话，把抬头和税号发我就行。',
      ],
    ),
    ChatSession(
      id: 's5',
      name: '张主编',
      nameEn: 'Chief Editor Zhang',
      avatarText: '张',
      seed: const ColorSeed(Color(0xFF9C27B0), Color(0xFFBA68C8)),
      lastMessage: '稿费已经打到你账户了',
      lastMessageEn: 'Payment sent to your account',
      time: now.subtract(const Duration(hours: 5)),
      messages: const [],
      replies: const [
        '这个选题做得很扎实，下周再跟进一篇。',
        '稿费走的是财务月度结算，月底统一打款。',
        '标题再克制一点，不用追热点式的表达。',
      ],
    ),
    ChatSession(
      id: 's6',
      name: '寰宇支付',
      nameEn: 'Huanyu Pay',
      avatarText: '支',
      seed: const ColorSeed(Color(0xFF1677FF), Color(0xFF00A0FF)),
      lastMessage: '您有一笔 128.00 元的转账待确认',
      lastMessageEn: 'A transfer of 128.00 is pending',
      time: now.subtract(const Duration(days: 1)),
      official: true,
      messages: const [],
      replies: const [
        '您的账单可在「我的-账单」里查看明细。',
        '账户安全等级已提升到最高，已完成风险评估。',
        '如需调整免密支付额度，可在支付设置里操作。',
      ],
    ),
    ChatSession(
      id: 's7',
      name: '云谷食品旗舰店',
      nameEn: 'Yungu Foods Flagship',
      avatarText: '云',
      seed: const ColorSeed(Color(0xFF8E2DE2), Color(0xFF4A00E0)),
      lastMessage: '挂耳咖啡今天下单，48 小时内发出',
      lastMessageEn: 'Order today, ships within 48h',
      time: now.subtract(const Duration(minutes: 45)),
      official: true,
      messages: const [],
      replies: const [
        '亲，现在下单有「第二件半价」活动哦~',
        '我们有现货，付款后 48 小时内发出。',
        '已经是直播间专属价了，不能再优惠啦。',
        '咖啡豆是保山产区中深烘焙，适合做奶咖。',
      ],
    ),
    ChatSession(
      id: 's8',
      name: '本地生活客服',
      nameEn: 'Local Life Support',
      avatarText: '生',
      seed: const ColorSeed(Color(0xFFFF9800), Color(0xFFFFB74D)),
      lastMessage: '您的团购券已核销成功',
      lastMessageEn: 'Your voucher has been redeemed',
      time: now.subtract(const Duration(hours: 2)),
      official: true,
      messages: const [],
      replies: const [
        '您好，团购券支持随时退、过期自动退。',
        '券码已生成，到店出示核销码即可。',
        '外卖订单预计 30 分钟送达，骑手已接单。',
      ],
    ),
  ];

  // ============================================================
  // 小程序
  // ============================================================
  static const List<MiniApp> miniApps = [
    MiniApp(
      id: 'm1',
      name: '寰宇新闻',
      desc: '看新闻、追热点，随时掌握天下事',
      icon: Icons.article_outlined,
      seed: ColorSeed(Color(0xFF1677FF), Color(0xFF3F8CFF)),
      category: '资讯',
    ),
    MiniApp(
      id: 'm2',
      name: '寰宇商城',
      desc: '精选好物，一键下单',
      icon: Icons.shopping_bag_outlined,
      seed: ColorSeed(Color(0xFFFE2C55), Color(0xFFFF6B8B)),
      category: '购物',
    ),
    MiniApp(
      id: 'm3',
      name: '寰宇出行',
      desc: '打车、公交、航班一站式查询',
      icon: Icons.directions_car_outlined,
      seed: ColorSeed(Color(0xFF00B4DB), Color(0xFF0083B0)),
      category: '出行',
    ),
    MiniApp(
      id: 'm4',
      name: '生活缴费',
      desc: '水电燃气，足不出户',
      icon: Icons.receipt_long_outlined,
      seed: ColorSeed(Color(0xFF43A047), Color(0xFF66BB6A)),
      category: '生活',
    ),
    MiniApp(
      id: 'm5',
      name: '寰宇健康',
      desc: '预约挂号、健康咨询',
      icon: Icons.medical_services_outlined,
      seed: ColorSeed(Color(0xFF8E24AA), Color(0xFFAB47BC)),
      category: '医疗',
    ),
    MiniApp(
      id: 'm6',
      name: '寰宇课堂',
      desc: '在线课程与直播学习',
      icon: Icons.school_outlined,
      seed: ColorSeed(Color(0xFFF4511E), Color(0xFFFF7043)),
      category: '教育',
    ),
    MiniApp(
      id: 'm7',
      name: '本地生活',
      desc: '外卖团购酒店，一键搞定',
      icon: Icons.local_offer_outlined,
      seed: ColorSeed(Color(0xFFFF9800), Color(0xFFFFB74D)),
      category: '生活',
    ),
    MiniApp(
      id: 'm8',
      name: '寰宇支付',
      desc: '收付款、账单、理财',
      icon: Icons.account_balance_wallet_outlined,
      seed: ColorSeed(Color(0xFF1677FF), Color(0xFF00A0FF)),
      category: '金融',
    ),
  ];

  // ============================================================
  // 账单（初始值，后续每笔支付/退款都会追加）
  // ============================================================
  static List<BillItem> initialBills() => [
        const BillItem(
          title: '稿费结算',
          titleEn: 'Article payment',
          time: '今天 09:12',
          amount: 1280.00,
          type: 'in',
          icon: Icons.arrow_downward,
          category: '转账',
        ),
        const BillItem(
          title: '商城订单 · 无线蓝牙耳机',
          titleEn: 'Shop order · Earbuds',
          time: '今天 08:40',
          amount: -299.00,
          type: 'out',
          icon: Icons.shopping_bag_outlined,
          category: '商城',
        ),
        const BillItem(
          title: '转账 - 林记者',
          titleEn: 'Transfer · Reporter Lin',
          time: '昨天 21:05',
          amount: -128.00,
          type: 'out',
          icon: Icons.swap_horiz,
          category: '转账',
        ),
        const BillItem(
          title: '直播打赏分成',
          titleEn: 'Live gift sharing',
          time: '昨天 19:30',
          amount: 862.50,
          type: 'in',
          icon: Icons.monetization_on_outlined,
          category: '直播',
        ),
        const BillItem(
          title: '会员订阅',
          titleEn: 'Membership',
          time: '9月15日',
          amount: -25.00,
          type: 'out',
          icon: Icons.card_membership_outlined,
          category: '会员',
        ),
        const BillItem(
          title: '本地生活 · 老碗村双人套餐',
          titleEn: 'Local deal · Noodle set',
          time: '9月14日',
          amount: -98.00,
          type: 'out',
          icon: Icons.local_offer_outlined,
          category: '团购',
        ),
        const BillItem(
          title: '商城订单 · 云南挂耳咖啡',
          titleEn: 'Shop order · Drip coffee',
          time: '9月13日',
          amount: -69.90,
          type: 'out',
          icon: Icons.shopping_bag_outlined,
          category: '商城',
        ),
        const BillItem(
          title: '广告分成 · 信息流',
          titleEn: 'Ad revenue · Feed',
          time: '9月12日',
          amount: 3260.80,
          type: 'in',
          icon: Icons.trending_up,
          category: '直播',
        ),
        const BillItem(
          title: '话费充值 · 10086',
          titleEn: 'Top up · Mobile',
          time: '9月11日',
          amount: -100.00,
          type: 'out',
          icon: Icons.phone_android,
          category: '充值',
        ),
        const BillItem(
          title: '退款 · 智能手环',
          titleEn: 'Refund · Smart band',
          time: '9月10日',
          amount: 249.00,
          type: 'in',
          icon: Icons.replay,
          category: '商城',
        ),
        const BillItem(
          title: '本地生活 · 西溪湿地门票',
          titleEn: 'Local deal · Wetland ticket',
          time: '9月8日',
          amount: -110.00,
          type: 'out',
          icon: Icons.local_offer_outlined,
          category: '团购',
        ),
        const BillItem(
          title: '工资代发 · 寰宇传媒',
          titleEn: 'Salary · Huanyu Media',
          time: '9月5日',
          amount: 18650.00,
          type: 'in',
          icon: Icons.account_balance_wallet_outlined,
          category: '转账',
        ),
      ];

  // ============================================================
  // 会话初始历史（存在 Store 里，发送新消息会真实追加）
  // ============================================================
  static Map<String, List<ChatMessage>> initialMessages() => {
        's1': [
          ChatMessage(
            id: 's1_m1',
            from: 's1',
            text: '早，今天国内频道还差两篇稿子',
            textEn: 'Morning, we still need two articles for China channel',
            time: now.subtract(const Duration(hours: 2, minutes: 20)),
          ),
          ChatMessage(
            id: 's1_m2',
            from: 'me',
            text: '已经排好了，9 点前一定到位',
            textEn: 'Already scheduled, will be ready before 9am',
            time: now.subtract(const Duration(hours: 2, minutes: 10)),
          ),
          ChatMessage(
            id: 's1_m3',
            from: 's1',
            text: '今天的头条稿已经过审，可以发布了',
            textEn: 'Today\'s headline is approved, go publish it',
            time: now.subtract(const Duration(minutes: 3)),
          ),
        ],
        's2': [
          ChatMessage(
            id: 's2_m1',
            from: 's2',
            text: '现场图片我上传到你邮箱了',
            textEn: 'I uploaded the photos to your mailbox',
            time: now.subtract(const Duration(minutes: 28)),
          ),
        ],
        's3': [
          ChatMessage(
            id: 's3_m1',
            from: 's3',
            text: '晚上回来吃饭吗',
            textEn: 'Are you coming home for dinner?',
            time: now.subtract(const Duration(hours: 1, minutes: 5)),
          ),
        ],
        's4': [
          ChatMessage(
            id: 's4_m1',
            from: 's4',
            text: '您好，您的订单已发货，请注意查收',
            textEn: 'Hello, your order has been shipped',
            time: now.subtract(const Duration(minutes: 12)),
          ),
          ChatMessage(
            id: 's4_m2',
            from: 's4',
            text: '需要发票的话把抬头和税号发我就行。',
            textEn: 'Send me the invoice title if you need one.',
            time: now.subtract(const Duration(minutes: 10)),
          ),
        ],
        's5': [
          ChatMessage(
            id: 's5_m1',
            from: 's5',
            text: '稿费已经打到你账户了',
            textEn: 'Payment has been sent to your account',
            time: now.subtract(const Duration(hours: 5)),
          ),
        ],
        's6': [
          ChatMessage(
            id: 's6_m1',
            from: 's6',
            text: '您有一笔 128.00 元的转账待确认',
            textEn: 'A transfer of ¥128.00 is pending confirmation',
            time: now.subtract(const Duration(days: 1)),
          ),
        ],
        's7': [
          ChatMessage(
            id: 's7_m1',
            from: 's7',
            text: '亲，挂耳咖啡今天下单，48 小时内发出~',
            textEn: 'Order the drip coffee today and it ships within 48h',
            time: now.subtract(const Duration(minutes: 45)),
          ),
        ],
        's8': [
          ChatMessage(
            id: 's8_m1',
            from: 's8',
            text: '您的团购券已核销成功',
            textEn: 'Your voucher has been redeemed',
            time: now.subtract(const Duration(hours: 2)),
          ),
        ],
      };

  /// 自动回复语料（默认兜底）
  static const List<String> defaultReplies = [
    '收到，我这边处理一下。',
    '好的，稍后给你答复。',
    '这个我需要确认一下再回你。',
    '没问题，按你说的来。',
  ];
}
